# fly.toml app configuration file generated for vectordb-service on 2024-06-01T01:09:31+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vectordb-service'
primary_region = 'lhr'

[build]
  image = 'chromadb/chroma:0.4.25.dev93'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "chromadb"
  destination = "/chroma/chroma"
  initial_size = "50gb"